"""Antibiotics lists."""
# pylint: disable=invalid-name


lstAntibioticIV = ['AMIKACIN', 'AMPICILLIN', 'AMPICILLIN-SULBACTAM', 'AZITHROMYCIN', 'AZTREONAM', 'CEFAMANDOLE',
                   'CEFAZOLIN', 'CEFEPIME', 'CEFMETAZOLE', 'CEFONICID', 'CEFOPERAZONE', 'CEFOTAXIME', 'CEFOTETAN',
                   'CEFOXITIN', 'CEFTAROLINE', 'CEFTAZIDIME', 'CEFTAZIDIME-AVIBACTAM', 'CEFTIZOXIME',
                   'CEFTOLOZANE-TAZOBACTAM', 'CEFTRIAXONE', 'CEFUROXIME', 'CEPHALOTHIN', 'CEPHAPIRIN',
                   'CHLORAMPHENICOL', 'CIPROFLOXACIN', 'CLINDAMYCIN', 'CLOXACILLIN', 'COLISTIN', 'DALBAVANCIN',
                   'DAPTOMYCIN', 'DORIPENEM', 'DOXYCYCLINE', 'ERTAPENEM', 'GATIFLOXACIN', 'GENTAMICIN', 'IMIPENEM',
                   'KANAMYCIN', 'LEVOFLOXACIN', 'LINCOMYCIN', 'LINEZOLID', 'MEROPENEM', 'METHICILLIN',
                   'METRONIDAZOLE', 'MEZLOCILLIN', 'MINOCYCLINE', 'MOXIFLOXACIN', 'NAFCILLIN', 'ORITAVANCIN',
                   'OXACILLIN', 'PENICILLIN', 'PIPERACILLIN', 'PIPERACILLIN-TAZOBACTAM', 'POLYMYXIN B',
                   'QUINUPRISTIN-DALFOPRISTIN', 'STREPTOMYCIN', 'TEDIZOLID', 'TELAVANCIN', 'TICARCILLIN',
                   'TICARCILLIN-CLAVULANATE', 'TIGECYCLINE', 'TOBRAMYCIN', 'SULFAMETHOXAZOLE-TRIMETHOPRIM',
                   'VANCOMYCIN']
lstAntibioticPO = ['AMOXICILLIN-CLAVULANATE', 'AMOXICILLIN', 'AMPICILLIN', 'AZITHROMYCIN', 'CEFACLOR',
                   'CEFADROXIL', 'CEFDINIR', 'CEFDITOREN', 'CEFIXIME', 'CEFPODOXIME', 'CEFPROZIL', 'CEFTIBUTEN',
                   'CEFUROXIME', 'CEPHALEXIN', 'CEPHRADINE', 'CHLORAMPHENICOL', 'CINOXACIN', 'CIPROFLOXACIN',
                   'CLARITHROMYCIN', 'CLINDAMYCIN', 'CLOXACILLIN', 'DICLOXACILLIN', 'DOXYCYCLINE', 'FIDAXOMICIN',
                   'FOSFOMYCIN', 'GATIFLOXACIN', 'LEVOFLOXACIN', 'LINCOMYCIN', 'LINEZOLID', 'METRONIDAZOLE',
                   'MINOCYCLINE', 'MOXIFLOXACIN', 'NITROFURANTOIN', 'NORFLOXACIN', 'OFLOXACIN', 'PENICILLIN',
                   'PIVAMPICILLIN', 'RIFAMPIN', 'SULFADIAZINE', 'SULFADIAZINE-TRIMETHOPRIM', 'SULFAMETHOXAZOLE',
                   'SULFISOXAZOLE', 'TEDIZOLID', 'TELITHROMYCIN', 'TETRACYCLINE', 'TRIMETHOPRIM',
                   'SULFAMETHOXAZOLE-TRIMETHOPRIM', 'VANCOMYCIN']

lstAntifungalIV = ['AMPHOTERICIN B', 'ANIDULAFUNGIN', 'CASPOFUNGIN', 'FLUCONAZOLE', 'ITRACONAZOLE', 'MICAFUNGIN',
                   'POSACONAZOLE', 'VORICONAZOLE']
lstAntifungalPO = ['FLUCONAZOLE', 'ITRACONAZOLE', 'POSACONAZOLE', 'VORICONAZOLE']

lstAntiviralIV = ['ACYCLOVIR', 'GANCICLOVIR', 'CIDOFOVIR', 'FOSCARNET', 'PERAMIVIR']
lstAntiviralPO = ['OSELTAMIVIR']

lstRemoveDrug = ['INTRAPERITONEAL', 'INTRATHECAL',
                 'CREAM', 'VAGINAL', 'TOPICAL', 'INHALATION', 'IR ONLY', ' NEBU',
                 'OPHTHALMIC', ' OPHTH', 'DROPS', 'OINTMENT', ' OINT']
lstRemoveStr = ['_', 'IVPB', 'INFUSION', 'INJECTION', 'BOLUS', 'ORAL', 'LIQUID', ' CAPSULE',
                'SUBSTANCE', 'CLASS OF ANTIBIOTIC', ' TABLET', ' SOLUTION', 'SYRINGE',
                'SUSPENSION', 'INTRAMUSCULAR', 'CENTRAL', 'MINI-BAG PLUS', 'LIPOSOMAL',
                'HYDROCHLORIDE', 'SODIUM', 'SULFATE', 'AXETIL', 'PALMITATE', 'MONOHYDRATE', 'HYCLATE',
                ' DS', ' DR', ' ER', ' SS', ' INJ.', ' INJ', ' IV ', ' TAB', ' SOLN', ' SUSP',
                'HUP']

lstAdministrationStatusKeep = ['Given', 'NewBag', 'RateVerify', 'RateChange', 'Inf Start', 'Restarted',
                               'IV PUSH', 'Given/Other', 'Bolus/Bag', 'FeedingGiven', 'Continued OR',
                               'Anes Contin', 'Bolus', 'Syringe/Cart', 'PUMP START', 'Refused']
